#!/bin/bash
a=10
b=20

sum=$(( $a + $b ))
echo "the sum of $a and  $b is = $sum"
subtract=$(( $a - $b ))
echo "the subtract of $a and  $b is = $subtract"
product=$(( $a * $b ))
echo "the product of $a and  $b is = $product"
division=$(( $a / $b ))
echo "the division of $a and  $b is = $division"

